-- DDL

DROP SEQUENCE SEQ_GEN_SEQUENCE RESTRICT;
CREATE SEQUENCE SEQ_GEN_SEQUENCE start with 0 INCREMENT BY 50  AS INTEGER;


CREATE TABLE STUDY_MEETING (
    ID INTEGER PRIMARY KEY,
    TITLE VARCHAR(128) NOT NULL,
    SUB_TITLE VARCHAR(128) NOT NULL,
    CONTEXT VARCHAR(1024) NOT NULL,
    EXHIBITION_DATE DATE NOT NULL,
    PARTICIPANT_COUNT INTEGER 
);

COMMENT ON TABLE STUDY_MEETING IS '勉強会';
COMMENT ON COLUMN STUDY_MEETING.ID IS 'ID';
COMMENT ON COLUMN STUDY_MEETING.TITLE IS 'タイトル';
COMMENT ON COLUMN STUDY_MEETING.SUB_TITLE IS 'サブタイトル';
COMMENT ON COLUMN STUDY_MEETING.CONTEXT IS '内容';
COMMENT ON COLUMN STUDY_MEETING.EXHIBITION_DATE IS '開催日';
COMMENT ON COLUMN STUDY_MEETING.PARTICIPANT_COUNT IS '参加者数';

DROP TABLE  TOTAL_OF_STUDY_MEETING;
CREATE TABLE TOTAL_OF_STUDY_MEETING (
	ID INTEGER PRIMARY KEY,
	TITLE VARCHAR(128) NOT NULL ,
	FROM_DATE DATE NOT NULL,
	TO_DATE DATE NOT NULL,
	TIMES INTEGER NOT NULL,
	TOTAL_PARTICIPANT_COUNT INTEGER NOT NULL,
        SUMMARY_DATE DATE NOT NULL
);

COMMENT ON TABLE TOTAL_OF_STUDY_MEETING IS '勉強会集計';
COMMENT ON COLUMN TOTAL_OF_STUDY_MEETING.ID IS 'ID';
COMMENT ON COLUMN TOTAL_OF_STUDY_MEETING.TITLE IS 'タイトル';
COMMENT ON COLUMN TOTAL_OF_STUDY_MEETING.FROM_DATE IS '集計開始日';
COMMENT ON COLUMN TOTAL_OF_STUDY_MEETING.TO_DATE IS '集計終了日';
COMMENT ON COLUMN TOTAL_OF_STUDY_MEETING.TIMES IS '開催回数';
COMMENT ON COLUMN TOTAL_OF_STUDY_MEETING.TOTAL_PARTICIPANT_COUNT IS 'のべ参加者数';
COMMENT ON COLUMN TOTAL_OF_STUDY_MEETING.SUMMARY_DATEIS '集計日';